external_data_schema:
  fixed_acidity: float64
  volatile_acidity: float64
  citric_acid: float64
  residual_sugar: float64
  chlorides: float64
  free_sulfur_dioxide: float64
  total_sulfur_dioxide: float64
  density: float64
  pH: float64
  sulphates: float64
  alcohol: float64
  color: object
  quality: int64


raw_data_schema:
  features:
    fixed_acidity: float64
    volatile_acidity: float64
    citric_acid: float64
    residual_sugar: float64
    chlorides: float64
    free_sulfur_dioxide: float64
    total_sulfur_dioxide: float64
    density: float64
    pH: float64
    sulphates: float64
    alcohol: float64
  target:
    quality: int64